### ISSUE TITLE
Enhancement Request: Add Support to Export XLIFF File Types

### ISSUE THREAD

**Issue by marchani** [sporteasy/python-poeditor#6]
This is an enhancement request to add support to export XLIFF file types in POEditorAPI.export().

This is an excellent API wrapper for Python to POEditor API and adding support to export XLIFF file types (which is a file format already supported according to the documentation of POEditor API: https://poeditor.com/docs/api#projects_export) may make it even more useable for iOS development.

**Comment by charles-vdulac** [comment]
Did by your PR #7. Thanks
